version: '3'

services:
    session-service:
        build: ../session-service
        image: session-service:0.0.1
        ports:
            - "8081:8080"
        restart: on-failure
        deploy:
            resources:
                limits:
                  cpus: '0.5'
                  memory: 512M
                reservations:
                  cpus: '0.25'
                  memory: 128M
    message-service:
        build: ../message-service
        image: message-service:0.0.1
        ports:
            - "8080:8080"
        restart: on-failure
        deploy:
            resources:
                limits:
                  cpus: '0.5'
                  memory: 512M
                reservations:
                  cpus: '0.25'
                  memory: 128M
    