openapi: "3.0.0"

info:
  version: 1.0.0
  title: Simple API overview

servers:
  - url: http://localhost:8081

paths:
  /session:
    post:
      summary: saveSession
      operationId: saveSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionBody'
      responses:
        '200':
          description: ok

components:
  schemas:
    SessionBody:
      type: object
      description: Модель сессии
      properties:
        id:
          description: Идентификатор
          type: string
