openapi: "3.0.0"

info:
  version: 1.0.0
  title: Simple API overview

servers:
  - url: http://localhost:8081

paths:
  /session:
    post:
      summary: saveSession
      operationId: saveSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionBody'
      responses:
        '200':
          description: ok
    get:
      summary: getSession
      operationId: getSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionBody'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionBody'
    delete:
      summary: deleteSession
      operationId: deleteSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionBody'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionBody'

components:
  schemas:
    SessionBody:
      type: object
      description: Модель сессии
      properties:
        senderLoginId:
          description: Идентификатор
          type: string
        recipientLoginId:
          description: Идентификатор
          type: string
        text:
          type: string
