name: Verify type labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
      

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/match-label-action@v5
        with:
          allowed: 'type:bug, type:feature, type:documentation, type:config'