name: Release checks

on:
  pull_request:
    branches:
    - master
    types:
    - opened
    - labeled
    - unlabeled

jobs:
  includes_version_bump:
    name: Labels
    runs-on: ubuntu-latest
    steps:
    - name: Check PR labels
      uses: zwaldowski/match-label-action@v4
      with:
        allowed: bug, feature, documentation, config
