jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run script file
      run: |-
         chmod +x ./github/workflow/workflows.sh
         ./github/workflow/workflows.sh
      shell: bash
